services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:8000
    volumes:
      - .env:/app/.env
      - ./app:/app/app
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - TZ=Asia/Shanghai
    networks:
      - redis_default

networks:
  redis_default:
    external: true

