[core]
# you can use "debug", "info", "warn", "error"
log_level = "debug"

[db]
database_url = "sqlite3:data/sqlite3.db"

[telegram]
token = "1234567890:abcdefghijklmnopqrstuvwxyz"

[yandere]
rss_url = "https://yande.re/post/popular_recent"
