name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux, windows]
        include:
          - build: linux
            os: ubuntu-22.04
            rust: nightly
            target: x86_64-unknown-linux-musl
            archive-name: pop_yandere_bot-linux.tar.gz
          - build: windows
            os: windows-2022
            rust: nightly-x86_64-msvc
            target: x86_64-pc-windows-msvc
            archive-name: pop_yandere_bot-windows.7z
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build binary
        run: cargo build --verbose --release --target ${{ matrix.target }}
        env:
          RUST_BACKTRACE: 1

      - name: Strip binary (linux and macos)
        if: matrix.build == 'linux' || matrix.build == 'macos'
        run: strip "target/${{ matrix.target }}/release/pop_yandere_bot"

      - name: Build archive
        shell: bash
        run: |
          mkdir archive
          cp LICENSE README.md archive/
          cd archive
          if [ "${{ matrix.build }}" = "windows" ]; then
            cp "../target/${{ matrix.target }}/release/pop_yandere_bot.exe" ./
            7z a "${{ matrix.archive-name }}" LICENSE README.md pop_yandere_bot.exe
          else
            cp "../target/${{ matrix.target }}/release/pop_yandere_bot" ./
            tar -czf "${{ matrix.archive-name }}" LICENSE README.md pop_yandere_bot
          fi
      - name: Upload archive
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.archive-name }}
          path: archive/${{ matrix.archive-name }}
